name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install -U pip
        python -m pip install -U flake8 isort
    - name: Lint
      run: |
        flake8 ./rest_framework_simplejwt ./tests
        isort --check-only --diff ./rest_framework_simplejwt ./tests

  tox:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
        DJANGO: [22, 30, 31, master]
        DRF: [310, 311, 312]
      exclude:
        - python-version: 3.7
          DJANGO: master
        - python-version: 3.8
          DJANGO: master

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install -U pip
        python -m pip install -U tox tox-gh-actions
    - name: Test with tox
      run: tox
      with:
        DJANGO: ${{ matrix.DJANGO }}
        DRF: ${{ matrix.DRF }}

  docs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install -U pip
    - name: Build docs
      run: make build-docs
